### ISSUE TITLE
Race condition while decoding

### ISSUE THREAD

**Issue by derselbst** [derselbst/ANPV#21]
The UI thread may call `SmartImageDecoder::reset` while decoding is still ongoing in the threadpool:

```
Thread 1 "anpv" hit Breakpoint 2, SmartImageDecoder::assertNotDecoding (this=<optimized out>) at /home/tom/EigeneProgramme/ANPV/src/decoders/SmartImageDecoder.cpp:401
401             throw std::logic_error("Operation not allowed, decoding is still ongoing.");
(gdb) bt
#0  SmartImageDecoder::assertNotDecoding (this=<optimized out>) at /home/tom/EigeneProgramme/ANPV/src/decoders/SmartImageDecoder.cpp:401
#1  0x0000000000470721 in SmartImageDecoder::reset (this=0x7fffc541d580) at /home/tom/EigeneProgramme/ANPV/src/decoders/SmartImageDecoder.cpp:326
#2  0x000000000045504c in DocumentView::Impl::clearScene (this=0xba02b0) at /home/tom/EigeneProgramme/ANPV/src/widgets/DocumentView.cpp:103
#3  0x000000000045211f in DocumentView::loadImage (this=0xbd2700, dec=...) at /home/tom/EigeneProgramme/ANPV/src/widgets/DocumentView.cpp:748
#4  DocumentView::loadImage (this=0xbd2700, e={...}) at /home/tom/EigeneProgramme/ANPV/src/widgets/DocumentView.cpp:725
#5  0x00000000004569c2 in DocumentView::Impl::goTo (this=0xba02b0, i=i@entry=-1) at /home/tom/EigeneProgramme/ANPV/src/widgets/DocumentView.cpp:336
#6  0x0000000000456b54 in DocumentView::Impl::createActions()::{lambda()#2}::operator()() const (this=<optimized out>) at /home/tom/EigeneProgramme/ANPV/src/widgets/DocumentView.cpp:371
#7  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, DocumentView::Impl::createActions()::{lambda()#2}>::call(DocumentView::Impl::createActions()::{lambda()#2}&, void**) (f=..., arg=<optimized out>)
    at /usr/include/qt6/QtCore/qobjectdefs_impl.h:146
#8  QtPrivate::Functor<DocumentView::Impl::createActions()::{lambda()#2}, 0>::call<QtPrivate::List<>, void>(DocumentView::Impl::createActions()::{lambda()#2}&, void*, void**) (f=..., arg=<optimized out>)
    at /usr/include/qt6/QtCore/qobjectdefs_impl.h:256
#9  QtPrivate::QFunctorSlotObject<DocumentView::Impl::createActions()::{lambda()#2}, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, 
    r=0x0, a=0xa30530, ret=0x1) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:420
```

**Comment by derselbst** [comment]
Resolved by #23
